/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppForm {
    }
    interface ComInput {
        "name": string;
    }
}
declare global {
    interface HTMLAppFormElement extends Components.AppForm, HTMLStencilElement {
    }
    var HTMLAppFormElement: {
        prototype: HTMLAppFormElement;
        new (): HTMLAppFormElement;
    };
    interface HTMLComInputElement extends Components.ComInput, HTMLStencilElement {
    }
    var HTMLComInputElement: {
        prototype: HTMLComInputElement;
        new (): HTMLComInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-form": HTMLAppFormElement;
        "com-input": HTMLComInputElement;
    }
}
declare namespace LocalJSX {
    interface AppForm {
    }
    interface ComInput {
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-form": AppForm;
        "com-input": ComInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-form": LocalJSX.AppForm & JSXBase.HTMLAttributes<HTMLAppFormElement>;
            "com-input": LocalJSX.ComInput & JSXBase.HTMLAttributes<HTMLComInputElement>;
        }
    }
}
